#!/bin/sh

if [ "$TOX4J_TARGET" = "host" ]; then
  case $TEST_GOAL in
    correctness)
      echo "Uploading coverage data..."
      tools/sbt coveralls
      ;;

    performance)
      # Nothing to do here.
      ;;
  esac
fi
