#!/bin/bash

set -ex

# Disable overrides.
unset CC
unset CXX

GLOBAL_CACHE="ivy2 sbt usr"
LOCAL_CACHE="target/benchmarks"

BASEDIR=$1
SOURCEDIR=$2

SBT="$SOURCEDIR/tools/sbt"
GH_USER=`git config --get remote.origin.url | grep -Po '(\w+)(?=/tox4j)'`

mkdir -p "$BASEDIR/cache/global"
mkdir -p "$BASEDIR/cache/local"
mkdir -p "$BASEDIR/git"

for dir in $GLOBAL_CACHE; do
  cache_dir="$BASEDIR/cache/global/$dir"
  if [ -d "$cache_dir" ]; then
    ln -s "$cache_dir" "$BASEDIR/.$dir"
  fi
done

for dir in $LOCAL_CACHE; do
  cache_dir="$BASEDIR/cache/local/`basename $dir`"
  if [ -d "$cache_dir" ]; then
    mkdir -p `dirname $dir`
    ln -s "$cache_dir" "$dir"
  else
    mkdir -p "$dir"
  fi
done

# Then for the local platform.
INSTALL() {
  BRANCH=${3:-master}

  cd "$BASEDIR/git"
  git clone --depth=1 --branch="$BRANCH" $1/$2.git \
    || git clone $1/$2.git
  cd $2

  git checkout $BRANCH
  git rev-parse HEAD > $2.HEAD
  if diff "$BASEDIR/cache/$2.HEAD" $2.HEAD; then
    return
  fi

  mv $2.HEAD "$BASEDIR/cache"

  # Generate autotools stuff.
  if [ ! -f configure ]; then
    ./autogen.sh --prefix="$BASEDIR/.usr" $4
  fi

  # If autogen.sh didn't also run configure,
  if [ ! -f config.log ]; then
    # we have a vpath build.
    mkdir -p _build
    cd _build
    # Run configure once.
    if [ ! -f config.log ]; then
      ../configure --prefix="$BASEDIR/.usr" $4
    fi
  fi

  # Then build and install.
  make -j4
  make install

  git clean -fdx
}

# We need the protoc binary for the host platform.
INSTALL https://github.com/google protobuf tags/v2.6.1

case "$TOX4J_TARGET" in
  *android*)
    cd $BASEDIR
    wget http://dl.google.com/android/ndk/android-ndk-$ANDROID_NDK_VERSION-linux-x86_64.bin
    NDK_EXCLUDES=$SOURCEDIR/tools/ndk-excludes.txt
    7z x android-ndk-$ANDROID_NDK_VERSION-linux-x86_64.bin `sed 's/^/ -xr!/g' $NDK_EXCLUDES` | awk '/^Extracting/ { i++; if (i > 50) {print; i = 0}}'
    rm android-ndk-$ANDROID_NDK_VERSION-linux-x86_64.bin

    cd "$SOURCEDIR/android"
    ./build-deps.sh
    ;;

  *)
    INSTALL https://github.com/yasm       yasm
    INSTALL https://git.chromium.org/webm libvpx        master          "--enable-pic --enable-shared"
    INSTALL https://github.com/jedisct1   libsodium
    INSTALL git://git.opus-codec.org      opus
    INSTALL https://github.com/irungentoo toxcore
    ;;
esac

# Install tox4j organisation dependencies.
for repo in sbt-tox4j linters; do
  cd "$BASEDIR/git"
  git clone --depth=1 https://github.com/$GH_USER/$repo
  cd $repo
  make install SBT="$SBT"
done

# Install the required Java/Scala packages.
cd $SOURCEDIR
$SBT update

for dir in $GLOBAL_CACHE; do
  cache_dir="$BASEDIR/cache/global/$dir"
  if [ ! -d "$cache_dir" ]; then
    mv "$BASEDIR/.$dir" "$cache_dir"
    ln -s "$cache_dir" "$BASEDIR/.$dir"
  fi
done

for dir in $LOCAL_CACHE; do
  cache_dir="$BASEDIR/cache/local/`basename $dir`"
  if [ ! -d "$cache_dir" -a -d "$dir" ]; then
    mv "$dir" "$cache_dir"
    ln -s "$cache_dir" "$dir"
  fi
done

# Don't log the rest of the commands.
set +x

# Prepare for tests or benchmarks.
case "$TEST_GOAL" in
  correctness)
    # Nothing to do here.
    ;;

  performance)
    echo "Fetching tox4j website sources for benchmark uploads"
    git clone "https://$GH_TOKEN@github.com/tox4j/tox4j.github.io" $SOURCEDIR/.web
    cd $SOURCEDIR/.web
    git config user.name "$GIT_NAME"
    git config user.email "$GIT_EMAIL"
    ;;
esac
