package im.tox.tox4j.impl.jni;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * Mark methods that are generated by JniMethodImpls.
 */
@Retention(RetentionPolicy.RUNTIME)
public @interface AutoGenerated {
  /**
   * Override the C function name this native method should call.
   */
  String value() default "";
}
