#undef Tox
#undef ToxAV
#undef toxav_new
#undef toxav_kill
#undef toxav_get_tox
#undef toxav_iteration_interval
#undef toxav_iteration
#undef toxav_options_default
#undef toxav_options_new
#undef toxav_options_free
#undef toxav_analyse_options
#undef toxav_call
#undef toxav_callback_call
#undef toxav_answer
#undef toxav_call_control
#undef toxav_callback_call_control
#undef toxav_change_options
#undef toxav_callback_change_options
#undef toxav_friend_get_options
#undef toxav_callback_request_video_frame
#undef toxav_send_video_frame
#undef toxav_callback_request_audio_frame
#undef toxav_send_audio_frame
#undef toxav_callback_receive_video_frame
#undef toxav_callback_receive_audio_frame
