#undef Tox
#undef ToxAV
#undef toxav_new
#undef toxav_kill
#undef toxav_get_tox
#undef toxav_iteration_interval
#undef toxav_iteration
#undef toxav_call
#undef toxav_callback_call
#undef toxav_answer
#undef toxav_call_control
#undef toxav_callback_call_control
#undef toxav_set_audio_bit_rate
#undef toxav_set_video_bit_rate
#undef toxav_callback_request_video_frame
#undef toxav_send_video_frame
#undef toxav_callback_request_audio_frame
#undef toxav_send_audio_frame
#undef toxav_callback_receive_video_frame
#undef toxav_callback_receive_audio_frame
