#undef Tox
#undef Tox_Options
#undef tox_options_default
#undef tox_options_new
#undef tox_options_free
#undef tox_new
#undef tox_kill
#undef tox_save_size
#undef tox_save
#undef tox_load
#undef tox_bootstrap
#undef tox_is_connected
#undef tox_callback_connection_status
#undef tox_get_port
#undef tox_iteration_time
#undef tox_iteration
#undef tox_get_address
#undef tox_set_nospam
#undef tox_get_nospam
#undef tox_get_self_client_id
#undef tox_get_secret_key
#undef tox_set_self_name
#undef tox_self_name_size
#undef tox_get_self_name
#undef tox_set_self_status_message
#undef tox_self_status_message_size
#undef tox_get_self_status_message
#undef tox_set_self_status
#undef tox_get_self_status
#undef tox_add_friend
#undef tox_add_friend_norequest
#undef tox_delete_friend
#undef tox_get_friend_number
#undef tox_get_friend_client_id
#undef tox_friend_exists
#undef tox_friend_list_size
#undef tox_get_friend_list
#undef tox_get_friend_name_size
#undef tox_get_friend_name
#undef tox_callback_friend_name
#undef tox_get_friend_status_message_size
#undef tox_get_friend_status_message
#undef tox_callback_friend_status_message
#undef tox_get_friend_status
#undef tox_callback_friend_status
#undef tox_get_friend_is_connected
#undef tox_callback_friend_connected
#undef tox_get_friend_is_typing
#undef tox_callback_friend_typing
#undef tox_set_typing
#undef tox_send_message
#undef tox_send_action
#undef tox_callback_read_receipt
#undef tox_callback_friend_request
#undef tox_callback_friend_message
#undef tox_callback_friend_action
#undef tox_hash
#undef tox_file_control
#undef tox_callback_file_control
#undef tox_file_send
#undef tox_file_send_chunk
#undef tox_callback_file_send_chunk
#undef tox_callback_file_receive
#undef tox_callback_file_receive_chunk
#undef tox_send_lossy_packet
#undef tox_callback_lossy_packet
#undef tox_send_lossless_packet
#undef tox_callback_lossless_packet
