#undef Tox
#undef Tox_Options
#undef tox_options_default
#undef tox_options_new
#undef tox_options_free
#undef tox_new
#undef tox_kill
#undef tox_save_size
#undef tox_save
#undef tox_load
#undef tox_bootstrap
#undef tox_get_connection_status
#undef tox_callback_connection_status
#undef tox_iteration_interval
#undef tox_iteration
#undef tox_self_get_address
#undef tox_self_set_nospam
#undef tox_self_get_nospam
#undef tox_self_get_client_id
#undef tox_self_get_private_key
#undef tox_self_set_name
#undef tox_self_get_name_size
#undef tox_self_get_name
#undef tox_self_set_status_message
#undef tox_self_get_status_message_size
#undef tox_self_get_status_message
#undef tox_self_set_status
#undef tox_self_get_status
#undef tox_friend_add
#undef tox_friend_add_norequest
#undef tox_friend_delete
#undef tox_friend_by_client_id
#undef tox_friend_get_client_id
#undef tox_friend_exists
#undef tox_friend_list_size
#undef tox_friend_list
#undef tox_friend_get_name_size
#undef tox_friend_get_name
#undef tox_callback_friend_name
#undef tox_friend_get_status_message_size
#undef tox_friend_get_status_message
#undef tox_callback_friend_status_message
#undef tox_friend_get_status
#undef tox_callback_friend_status
#undef tox_friend_get_connected
#undef tox_callback_friend_connected
#undef tox_friend_get_typing
#undef tox_callback_friend_typing
#undef tox_self_set_typing
#undef tox_send_message
#undef tox_send_action
#undef tox_callback_read_receipt
#undef tox_callback_friend_request
#undef tox_callback_friend_message
#undef tox_callback_friend_action
#undef tox_hash
#undef tox_file_control
#undef tox_callback_file_control
#undef tox_file_send
#undef tox_file_send_chunk
#undef tox_callback_file_request_chunk
#undef tox_callback_file_receive
#undef tox_callback_file_receive_chunk
#undef tox_send_lossy_packet
#undef tox_callback_friend_lossy_packet
#undef tox_send_lossless_packet
#undef tox_callback_friend_lossless_packet
#undef tox_get_dht_id
#undef tox_get_port
