#!/usr/bin/env perl

use common::sense;
use JSON::XS;

my $data = do { local $/; open my $fh, '<', 'exceptions.json' or die $!; decode_json <$fh> };

my $package = $data->[0];
my $exns = $data->[1];

for my $type (keys %$exns) {
   open my $fh, '>', "Tox${type}Exception.java"
      or die $!;

   my $codes = join ",\n", map { "    $_" } @{ $exns->{$type} };

   print $fh <<JAVA;
package im.tox.tox4j.$package.exceptions;

import im.tox.tox4j.annotations.NotNull;
import im.tox.tox4j.exceptions.ToxException;

public final class Tox${type}Exception extends ToxException {

  public enum Code {
$codes,
  }

  \@NotNull private final Code code;

  public Tox${type}Exception(\@NotNull Code code) {
    this.code = code;
  }

  \@Override
  \@NotNull
  public Code getCode() {
    return code;
  }

}
JAVA

}
