package im.tox.tox4j.crypto

object ToxCryptoConstants {

  /**
   * Length of salt in bytes.
   */
  final val SALT_LENGTH = 32

  /**
   * Number of bytes added to any encrypted data.
   */
  final val ENCRYPTION_EXTRA_LENGTH = 80

  /**
   * The number of bytes in a hash generated by tox_hash.
   */
  final val HASH_LENGTH = 32

}
