package im.tox.tox4j.crypto

object ToxCryptoConstants {

  /**
   * Length of salt in bytes.
   */
  final val SaltLength = 32

  /**
   * The number of bytes in a serialised [[ToxCrypto.PassKey]] without salt.
   * The serialised size is [[KeyLength]] + [[SaltLength]].
   */
  final val KeyLength = 32

  /**
   * Number of bytes added to any encrypted data.
   */
  final val EncryptionExtraLength = 80

  /**
   * The number of bytes in a hash generated by tox_hash.
   */
  final val HashLength = 32

  final val PublicKeyLength = 32
  final val SecretKeyLength = 32
  final val SharedKeyLength = 32
  final val NonceLength = 24

  final val ZeroBytes = 32
  final val BoxZeroBytes = 16

}
