package im.tox.tox4j.crypto

object ToxCryptoConstants {

  /**
   * Length of salt in bytes.
   */
  final val SALT_LENGTH = 32

  /**
   * The number of bytes in a serialised [[ToxCrypto.PassKey]] without salt.
   * The serialised size is [[KEY_LENGTH]] + [[SALT_LENGTH]].
   */
  final val KEY_LENGTH = 32

  /**
   * Number of bytes added to any encrypted data.
   */
  final val ENCRYPTION_EXTRA_LENGTH = 80

  /**
   * The number of bytes in a hash generated by tox_hash.
   */
  final val HASH_LENGTH = 32

  final val PUBLICKEY_BYTES = 32
  final val SECRETKEY_BYTES = 32
  final val NONCE_BYTES = 24
  final val ZERO_BYTES = 32
  final val BOXZERO_BYTES = 16

}
