#!/usr/bin/env perl

use common::sense;
use Data::Dumper;

local $Data::Dumper::Sortkeys = 1;
local $Data::Dumper::Terse = 1;
local $Data::Dumper::Indent = 1;

my $dep;

for my $file (@ARGV) {
   open my $fh, '<', $file
      or die "Could not open '$file' for reading: $!";

   my $class;
   for (<$fh>) {
      s/<(?>[^<>]|(?R))*>//g;

      if (/^Compiled from|^$|^  public static \{\};$|^    Code:$|^\}$/) {
         # Ignore
      }

      elsif (/^[a-z].*\b(?:class|interface)\b (.+) \{/) {
         my ($className, $extends, $implements) = $1 =~ /^(.+?)(?: extends (.+?))?(?: implements (.+?))?$/;
         my @super = (
            split ",", $extends,
            split ",", $implements,
         );
         $class = $dep->{$className} = {
            name => $className,
            super => \@super,
         };
      }

      elsif (/^  public static final ([^ ]+) [^ ]+;$/) {
         say $1;
      }

      elsif (/^  private \Q$class->{name}\E\((.*)\);$/) {
         say $1;
      }

      elsif (/^    +\d+: \w+[^\/]+(?:\/\/ (.*))?$/) {
         if ($1) {
            say $1;
         }
      }

      else {
         die $_;
      }
   }

   last
}

print Dumper $dep;
