#!/bin/sh

set -ex

PREFIX=$1
BASEURL=$2
REPO=$3
shift 3

TMPDIR=/tmp/git-install-$$

mkdir -p $PREFIX
mkdir -p $TMPDIR

cd $TMPDIR
git clone --depth=1 --branch="master" $BASEURL/$REPO.git \
  || git clone $BASEURL/$REPO.git
cd $REPO

git checkout master
git rev-parse HEAD > $REPO.HEAD
if diff "$PREFIX/$REPO.HEAD" $REPO.HEAD; then
  rm -rf $TMPDIR
  exit
fi

mv $REPO.HEAD "$PREFIX"

# Generate autotools stuff.
if [ ! -f configure ]; then
  ./autogen.sh --prefix="$PREFIX" "$@"
fi

# If autogen.sh didn't also run configure,
if [ ! -f config.log ]; then
  # we have a vpath build.
  mkdir -p _build
  cd _build
  # Run configure once.
  if [ ! -f config.log ]; then
    ../configure --prefix="$PREFIX" "$@"
  fi
fi

# Then build and install.
make -j4
make install

rm -rf $TMPDIR

# vim:sw=2
