#!/bin/sh

set -ex

PREFIX=$1

NDK_EXCLUDES="\
arch-mips
arch-x86
*/platforms/android-12
*/platforms/android-13
*/platforms/android-14
*/platforms/android-15
*/platforms/android-16
*/platforms/android-17
*/platforms/android-18
*/platforms/android-19
*/platforms/android-20
*/platforms/android-21
*/platforms/android-3
*/platforms/android-4
*/platforms/android-5
*/platforms/android-8
*/sources/cxx-stl/llvm-libc++*
*/tests
*/toolchains/*-4.9
*/toolchains/*-clang3.5
*/toolchains/aarch64*
*/toolchains/llvm-3.5
*/toolchains/mips*
*/toolchains/x86*"

NDK_VERSION=r10e
NDK_PACKAGE=android-ndk-$NDK_VERSION-linux-x86_64.bin

mkdir -p $PREFIX
cd $PREFIX

if [ ! -f $NDK_PACKAGE ]; then
  wget http://dl.google.com/android/ndk/$NDK_PACKAGE
fi
rm -rf android-ndk
7z x $NDK_PACKAGE `echo "$NDK_EXCLUDES" | sed 's/^/ -xr!/g'` | awk '/^Extracting/ { i++; if (i > 50) {print; i = 0}}'

mv android-ndk-$NDK_VERSION android-ndk
