#!/bin/sh

SBT=`dirname $0`/sbt-launch.jar
if [ ! -f "$SBT" ]; then
   wget -O "$SBT" https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.13.8/sbt-launch.jar
fi

SBT_OPTS="-Xms512M -Xmx1536M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M"
yes q | java $SBT_OPTS -jar $SBT "$@"
